"""empty message

Revision ID: 133b0541560e
Revises: 
Create Date: 2025-02-28 22:42:32.566675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133b0541560e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cordinadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rut', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_index(op.f('ix_cordinadores_id'), 'cordinadores', ['id'], unique=False)
    op.create_table('directores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rut', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_index(op.f('ix_directores_id'), 'directores', ['id'], unique=False)
    op.create_table('estudiantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rut', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('estudiante_regular', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_index(op.f('ix_estudiantes_id'), 'estudiantes', ['id'], unique=False)
    op.create_table('fechas_postulaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=False),
    sa.Column('is_asigned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inicio')
    )
    op.create_index(op.f('ix_fechas_postulaciones_id'), 'fechas_postulaciones', ['id'], unique=False)
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('id_director', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_director'], ['directores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departamentos_id'), 'departamentos', ['id'], unique=False)
    op.create_table('materias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('id_cordinador', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_cordinador'], ['cordinadores.id'], ),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materias_id'), 'materias', ['id'], unique=False)
    op.create_table('materias_usuario_notas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiantes.id'], ),
    sa.ForeignKeyConstraint(['id_materia'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materias_usuario_notas_id'), 'materias_usuario_notas', ['id'], unique=False)
    op.create_table('secciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_materia'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secciones_id'), 'secciones', ['id'], unique=False)
    op.create_table('ayudantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_seccion', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiantes.id'], ),
    sa.ForeignKeyConstraint(['id_seccion'], ['secciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ayudantes_id'), 'ayudantes', ['id'], unique=False)
    op.create_table('postulantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('id_materia_usuario_nota', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_materia_usuario_nota'], ['materias_usuario_notas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postulantes_id'), 'postulantes', ['id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('id_section', sa.Integer(), nullable=False),
    sa.Column('id_helper', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_helper'], ['ayudantes.id'], ),
    sa.ForeignKeyConstraint(['id_section'], ['secciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    op.create_table('reportes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contenido', sa.String(), nullable=False),
    sa.Column('id_ayudante', sa.Integer(), nullable=False),
    sa.Column('id_seccion', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_ayudante'], ['ayudantes.id'], ),
    sa.ForeignKeyConstraint(['id_seccion'], ['secciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportes_id'), 'reportes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reportes_id'), table_name='reportes')
    op.drop_table('reportes')
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_postulantes_id'), table_name='postulantes')
    op.drop_table('postulantes')
    op.drop_index(op.f('ix_ayudantes_id'), table_name='ayudantes')
    op.drop_table('ayudantes')
    op.drop_index(op.f('ix_secciones_id'), table_name='secciones')
    op.drop_table('secciones')
    op.drop_index(op.f('ix_materias_usuario_notas_id'), table_name='materias_usuario_notas')
    op.drop_table('materias_usuario_notas')
    op.drop_index(op.f('ix_materias_id'), table_name='materias')
    op.drop_table('materias')
    op.drop_index(op.f('ix_departamentos_id'), table_name='departamentos')
    op.drop_table('departamentos')
    op.drop_index(op.f('ix_fechas_postulaciones_id'), table_name='fechas_postulaciones')
    op.drop_table('fechas_postulaciones')
    op.drop_index(op.f('ix_estudiantes_id'), table_name='estudiantes')
    op.drop_table('estudiantes')
    op.drop_index(op.f('ix_directores_id'), table_name='directores')
    op.drop_table('directores')
    op.drop_index(op.f('ix_cordinadores_id'), table_name='cordinadores')
    op.drop_table('cordinadores')
    # ### end Alembic commands ###
