"""empty message

Revision ID: ad23dd2c167f
Revises: 
Create Date: 2024-11-21 15:20:56.097643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad23dd2c167f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fechas_postulaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inicio')
    )
    op.create_index(op.f('ix_fechas_postulaciones_id'), 'fechas_postulaciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fechas_postulaciones_id'), table_name='fechas_postulaciones')
    op.drop_table('fechas_postulaciones')
    # ### end Alembic commands ###
